version: "3.8"

services:
  php:
    container_name: php
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
        - "80:80"
    volumes:
        - ./html:/var/www/html/
        